# TODO more plugins can be lazily loaded

[[plugins]]
repo = "haya14busa/dein-command.vim"

[[plugins]]
repo = "morhetz/gruvbox"
# TODO this fails on first load
hook_add = """
  colorscheme gruvbox
"""

[[plugins]]
repo = "vim-airline/vim-airline"
hook_add = """
  let g:airline_powerline_fonts = 1

  if !exists("g:airline_symbols")
      let g:airline_symbols = {}
  endif
  let g:airline_symbols.maxlinenr = ""
"""

[[plugins]]
repo = "cespare/vim-toml"

[[plugins]]
repo = "neovimhaskell/haskell-vim"

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = "tpope/vim-repeat"

[[plugins]]
repo = "tpope/vim-sleuth"

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "Shougo/deoplete.nvim"
on_event = "InsertEnter"
hook_add = """
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#max_menu_width = 60
"""

[[plugins]]
repo = "vim-scripts/argtextobj.vim"

[[plugins]]
repo = "Shougo/neosnippet.vim"
depends = "neosnippet-snippets"
hook_add = """
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
              \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
"""
[[plugins]]
repo = "Shougo/neosnippet-snippets"

[[plugins]]
repo = "benekastah/neomake"
on_ft = [ "c", "h", "hs" ]
hook_post_source = """
  autocmd! BufWritePost,BufReadPost * Neomake
  autocmd! VimLeave * let g:neomake_verbose = 0
"""

[[plugins]]
repo = "scrooloose/nerdtree"
on_cmd = "NERDTreeToggle"
hook_add = """
  nnoremap <silent> <Leader>t :NERDTreeToggle<CR>
"""

[[plugins]]
repo = "majutsushi/tagbar"
on_cmd = "TagbarToggle"
hook_add = """
  nnoremap <silent> <Leader>T :TagbarToggle<CR>
"""

[[plugins]]
repo = "ludovicchabant/vim-gutentags"
on_source = "tagbar"

# cx, v_X -- exchange, cxc -- clear
[[plugins]]
repo = "tommcdo/vim-exchange"

# gc, :Commentary -- comment
[[plugins]]
repo = "tpope/vim-commentary"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "tpope/vim-surround"

[[plugins]]
repo = "tpope/vim-unimpaired"

[[plugins]]
repo = "Shougo/denite.nvim"
on_cmd = "Denite"

[[plugins]]
repo = "eagletmt/neco-ghc"
on_ft = "hs"
hook_post_source = """
  let g:haskellmode_completion_ghc = 0
  let g:necoghc_enable_detailed_browse = 1
"""
